# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "14c8601e-2d9e-4a4a-9db0-b0227766c429",
# META       "default_lakehouse_name": "LHDEVBRONZE",
# META       "default_lakehouse_workspace_id": "d021c3f1-8374-419e-87ab-d3d45db22fb1",
# META       "known_lakehouses": [
# META         {
# META           "id": "14c8601e-2d9e-4a4a-9db0-b0227766c429"
# META         }
# META       ]
# META     },
# META     "warehouse": {
# META       "default_warehouse": "c1b9ebc7-f6f6-4e5a-9608-93853db66c8f",
# META       "known_warehouses": [
# META         {
# META           "id": "c1b9ebc7-f6f6-4e5a-9608-93853db66c8f",
# META           "type": "Lakewarehouse"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Create a folder inside the Lakehouse Files area.
mssparkutils.fs.mkdirs("Files/Bronze/Raw/Stibo/Customer")


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE SCHEMA IF NOT EXISTS LHDEVBRONZE.bronze_staging

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE SCHEMA IF NOT EXISTS LHDEVBRONZE.control

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE SCHEMA IF NOT EXISTS LHDEVBRONZE.audit

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE SCHEMA IF NOT EXISTS LHDEVSILVER.silver

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.control.cfg_bronze_raw  (
# MAGIC     BRONZE_RAW_ENTITY_ID       INT            NOT NULL,
# MAGIC     INTERFACE_ID               VARCHAR(100)   NOT NULL,
# MAGIC     SOURCE_TYPE                VARCHAR(100)   NOT NULL,
# MAGIC     FABRIC_PIPELINE_NAME       VARCHAR(100)   NOT NULL,
# MAGIC     SOURCE_FILE_PATH           VARCHAR(500),
# MAGIC     FILE_NAME                  VARCHAR(255),
# MAGIC     DB_CONNECTION_NAME         VARCHAR(255),
# MAGIC     DB_TYPE                    VARCHAR(255),
# MAGIC     DB_HOST                    VARCHAR(255),
# MAGIC     DB_PORT                    VARCHAR(255),
# MAGIC     DB_NAME                    VARCHAR(255),
# MAGIC     DB_TABLE_NAME              VARCHAR(255),
# MAGIC     DB_QUERY                   VARCHAR(255),
# MAGIC     TARGET_FILE_PATH           VARCHAR(500)   NOT NULL,
# MAGIC     ISACTIVE                   VARCHAR(5)
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.control.cfg_bronze_staging  (
# MAGIC     BRONZE_STAGING_ENTITY_ID   INT            NOT NULL,
# MAGIC     INTERFACE_ID               VARCHAR(100)   NOT NULL,
# MAGIC     SOURCE_SYSTEM              VARCHAR(100)    NOT NULL,
# MAGIC     SOURCE_TYPE                VARCHAR(50)    NOT NULL,
# MAGIC     SOURCE_PATH                VARCHAR(500)   NOT NULL,
# MAGIC     PROCESSED_PATH             VARCHAR(500)   NOT NULL,
# MAGIC     QUARANTINE_PATH            VARCHAR(500)   NOT NULL,
# MAGIC     ROOT_SOURCE_PATH           VARCHAR(500)   NOT NULL,
# MAGIC     ROOT_PROCESSED_PATH        VARCHAR(500)   NOT NULL,
# MAGIC     ROOT_QUARANTINE_PATH       VARCHAR(500)   NOT NULL,
# MAGIC     RETENTION_DAYS             INT,
# MAGIC     SOURCE_OBJECT_NAME         VARCHAR(255)   NOT NULL,
# MAGIC     SOURCE_FILE_PATTERN        VARCHAR(255),
# MAGIC     SOURCE_FORMAT              VARCHAR(50),
# MAGIC     SOURCE_FILE_DELIMITER      VARCHAR(10),
# MAGIC     SOURCE_FILE_HEADER         VARCHAR(10),
# MAGIC     SOURCE_FILE_COMPRESSION    VARCHAR(50),
# MAGIC     FILE_SIZE_MIN_BYTES    VARCHAR(10),
# MAGIC     KEY_COLUMN                  VARCHAR(50),
# MAGIC     DELETE_COLUMN               VARCHAR(50),
# MAGIC     DELETE_COLUMN_VALUE         VARCHAR(50),
# MAGIC     TARGET_FORMAT              VARCHAR(50),
# MAGIC     TARGET_LAKEHOUSE           VARCHAR(255),
# MAGIC     TARGET_SCHEMA                VARCHAR(500)  NOT NULL,
# MAGIC     TARGET_TABLE_NAME         VARCHAR(255)     NOT NULL,
# MAGIC     TARGET_WRITE_MODE          VARCHAR(50)     NOT NULL,
# MAGIC     HISTORY_LOAD_INDICATOR     VARCHAR(5),
# MAGIC     HISTORY_TARGET_FORMAT      VARCHAR(50),
# MAGIC     HISTORY_TARGET_SCHEMA       VARCHAR(500),
# MAGIC     HISTORY_TARGET_TABLE_NAME VARCHAR(255),
# MAGIC     HISTORY_TARGET_WRITE_MODE  VARCHAR(50),
# MAGIC     RULE_VALIDATION_RESULTS_TABLE_NAME VARCHAR(255),
# MAGIC     SCHEMA_VALIDATION_RESULTS_TABLE_NAME VARCHAR(255),
# MAGIC     RECORD_IDENTIFIER_COLUMN VARCHAR(255),
# MAGIC     RECORD_IDENTIFIER_VALUE_COLUMN VARCHAR(255),
# MAGIC     VALIDATION_SOURCE_COLUMN VARCHAR(255),
# MAGIC     ISACTIVE                   VARCHAR(5)
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.control.cfg_silver (
# MAGIC     SILVER_ENTITY_ID INT  NOT NULL,   
# MAGIC     INTERFACE_ID      STRING     NOT NULL, 
# MAGIC     TABLE_NAME        STRING,  
# MAGIC     EXECUTION_ORDER  INT     NOT NULL,   
# MAGIC     NOTEBOOK_NAME    STRING  NOT NULL, 
# MAGIC     DELETE_KEY_COLUMN        STRING,
# MAGIC     DELETE_SRC_TABLE     STRING,
# MAGIC     DELETE_SRC_KEY_COLUMN STRING,
# MAGIC     DELETE_SRC_COLUMN STRING,
# MAGIC     DELETE_SRC_COLUMN_VALUE STRING,
# MAGIC     ISACTIVE         STRING
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.control.cfg_gold (
# MAGIC     GOLD_ENTITY_ID INT  NOT NULL,   
# MAGIC     INTERFACE_ID      STRING     NOT NULL, 
# MAGIC     TABLE_NAME        STRING,
# MAGIC     EXECUTION_ORDER  INT     NOT NULL,   
# MAGIC     STORED_PROCEDURE_NAME    STRING  NOT NULL,  
# MAGIC     ISACTIVE         STRING
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.control.cfg_interface (
# MAGIC     INTERFACE_ID   VARCHAR(50),
# MAGIC     INTERFACE_NAME VARCHAR(100)
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.control.cfg_expected_schema (
# MAGIC     INTERFACE_ID     STRING      NOT NULL,
# MAGIC     FILE_NAME        STRING      NOT NULL,
# MAGIC     SOURCE_TABLE_NAME STRING     NOT NULL,
# MAGIC     COLUMN_POSITION  INT         NOT NULL,
# MAGIC     COLUMN_NAME      STRING      NOT NULL,
# MAGIC     RECORD_IDENTIFIER STRING      NOT NULL,
# MAGIC     DATA_TYPE_VALIDATION        STRING,
# MAGIC     ACTIVE_FLAG      STRING
# MAGIC )

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE TABLE IF  NOT EXISTS LHDEVBRONZE.control.cfg_validation_rules_assignment (
# MAGIC     RULE_ASSIGNMENT_ID INT,
# MAGIC     INTERFACE_ID VARCHAR(255),
# MAGIC     RULE_TYPE  VARCHAR(255),
# MAGIC     TABLE_NAME VARCHAR(255),
# MAGIC     CONDITION_COLUMN VARCHAR(255),
# MAGIC     TARGET_COLUMN VARCHAR(255),
# MAGIC     RECORD_IDENTIFIER VARCHAR(255),
# MAGIC     SEVERITY_TYPE VARCHAR(50),
# MAGIC     IS_ACTIVE VARCHAR(50)
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.audit.ops_validation_results (
# MAGIC     BATCH_ID VARCHAR(255),
# MAGIC     RULE_ASSIGNMENT_ID INT, 
# MAGIC     INTERFACE_ID VARCHAR(255),
# MAGIC     RULE_TYPE  VARCHAR(255),
# MAGIC     SOURCE_NAME VARCHAR(255),
# MAGIC     COLUMN_NAME VARCHAR(255),
# MAGIC     RECORD_IDENTIFIER VARCHAR(255),
# MAGIC     RECORD_IDENTIFIER_VALUE VARCHAR(255),
# MAGIC     VALIDATION_STATUS VARCHAR(10), 
# MAGIC     IS_FIXED VARCHAR(10),
# MAGIC     FIXED_DATE TIMESTAMP,
# MAGIC     CREATED_DATE TIMESTAMP
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.audit.ops_schema_validation_results (
# MAGIC     BATCH_ID                    STRING,
# MAGIC     SOURCE_TYPE                 STRING,
# MAGIC     SOURCE_NAME                 STRING NOT NULL,
# MAGIC 	VALIDATION_STAGE            STRING NOT NULL,
# MAGIC     COLUMN_POSITION             INT,
# MAGIC     EXPECTED_COLUMN_NAME        STRING,
# MAGIC     ACTUAL_COLUMN_NAME          STRING,
# MAGIC     EXPECTED_DATA_TYPE          STRING,
# MAGIC     ACTUAL_DATA_TYPE            STRING,
# MAGIC     ATTRIBUTE_VALUE             STRING,
# MAGIC     RECORD_IDENTIFIER STRING, 
# MAGIC     RECORD_IDENTIFIER_VALUE     STRING,
# MAGIC     VALIDATION_STATUS           STRING NOT NULL,
# MAGIC     VALIDATION_MESSAGE          STRING,
# MAGIC     IS_FIXED                    STRING,
# MAGIC     FIXED_DATE                  TIMESTAMP,
# MAGIC     CREATED_DATE                TIMESTAMP   NOT NULL
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.audit.ops_pipeline_runs (
# MAGIC     BATCH_ID VARCHAR(100),
# MAGIC     LAYER VARCHAR(50),
# MAGIC     PIPELINE_ID VARCHAR(200),
# MAGIC     PIPELINE_RUN_ID VARCHAR(200),
# MAGIC     PIPELINE_NAME VARCHAR(200),
# MAGIC     START_TIME TIMESTAMP,
# MAGIC     END_TIME TIMESTAMP,
# MAGIC     WORKSPACE_ID VARCHAR(200),
# MAGIC     PARENT_PIPELINE_ID VARCHAR(200),
# MAGIC     PARENT_PIPELINE_RUN_ID VARCHAR(200),
# MAGIC     PARENT_PIPELINE_NAME VARCHAR(200),
# MAGIC     PIPELINE_STATUS VARCHAR(200)
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.audit.ops_error_log (
# MAGIC     BATCH_ID            VARCHAR(100),
# MAGIC     PIPELINE_NAME       VARCHAR(200),
# MAGIC     PIPELINE_ID         VARCHAR(100),
# MAGIC     PIPELINE_RUN_ID     VARCHAR(200),
# MAGIC     ACTIVITY_NAME       VARCHAR(200),
# MAGIC     ERROR_MESSAGE       VARCHAR(4000),
# MAGIC     ACTIVITY_TYPE       VARCHAR(100),
# MAGIC     ACTIVITY_START_TIME   TIMESTAMP,
# MAGIC     ACTIVITY_END_TIME     TIMESTAMP,
# MAGIC     CREATED_DATE             TIMESTAMP
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.audit.ops_delete_log(
# MAGIC     ATTRIBUTE_NAME STRING,
# MAGIC     ATTRIBUTE_VALUE STRING,
# MAGIC     EVENT_TYPE STRING,
# MAGIC     SOURCE_TABLE STRING,
# MAGIC     TARGET_TABLE STRING,
# MAGIC     DELETED_DATE TIMESTAMP,
# MAGIC     BATCH_ID STRING
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.audit.ops_ingestion_file_audit (
# MAGIC     BATCH_ID           VARCHAR(100),
# MAGIC     FILE_NAME          VARCHAR(255),
# MAGIC     FILE_PATH          VARCHAR(500),
# MAGIC     FILE_SIZE          BIGINT      ,
# MAGIC     STATUS             VARCHAR(50) ,
# MAGIC     SOURCE_SYSTEM      VARCHAR(100),
# MAGIC     FILE_ARRIVAL_UTC   TIMESTAMP,
# MAGIC     PIPELINE_RUN_ID    VARCHAR(100)
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.audit.ops_record_count_log (
# MAGIC     BATCH_ID        VARCHAR(50),
# MAGIC     SOURCE_TABLE    VARCHAR(100),
# MAGIC     TARGET_TABLE    VARCHAR(100),
# MAGIC     SOURCE_RECORDS  BIGINT      ,
# MAGIC     INSERT_RECORDS  BIGINT ,
# MAGIC     UPDATE_RECORDS  BIGINT,
# MAGIC     DELETE_RECORDS  BIGINT,
# MAGIC     CREATED_DATE    TIMESTAMP
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.bronze_staging.CUSTOMER_BRONZE_SNAPSHOT
# MAGIC (
# MAGIC ID	STRING,
# MAGIC EVENTTYPE STRING,
# MAGIC SOURCERECORDID	STRING,
# MAGIC SOURCESYSTEMID	STRING,
# MAGIC TITLE	STRING,
# MAGIC FORENAMES	STRING,
# MAGIC LASTNAME	STRING,
# MAGIC PERSONALNAMESUFFIX	STRING,
# MAGIC BIRTHDATE	STRING,
# MAGIC GENDER	STRING,
# MAGIC NATIONALINSURANCENUMBER	STRING,
# MAGIC NATIONALITY	STRING,
# MAGIC MARITALSTATUS	STRING,
# MAGIC EXCLUDEFROMDEDUPE	STRING,
# MAGIC TAXIDNUMBER	STRING,
# MAGIC TAXDOMICILE	STRING,
# MAGIC DEATHEVIDENCESEENDATE	STRING,
# MAGIC DECEASEDDATE	STRING,
# MAGIC DECEASEDNOTIFICATIONDATE	STRING,
# MAGIC DEACTIVATEDRECORD	STRING,
# MAGIC RELATIONSHIPENDDATE	STRING,
# MAGIC RELATIONSHIPSTARTDATE	STRING,
# MAGIC SENTFORDELETIONDATE	STRING,
# MAGIC SENTFORDELETIONUSER	STRING,
# MAGIC DELETEDINCORE	STRING,
# MAGIC DELETEDINMDM	STRING,
# MAGIC DELETIONDEDUPEEXCLUSION	STRING,
# MAGIC DORMANTACCOUNTFLAG	STRING,
# MAGIC MANUALEXCEPTIONFLAG	STRING,
# MAGIC MANUALEXCEPTIONREASON	STRING,
# MAGIC MANUALEXCEPTIONUSER	STRING,
# MAGIC MCNRFLAG	STRING,
# MAGIC OPENCOMPLAINTFLAG	STRING,
# MAGIC OPENLITIGATIONFLAG	STRING,
# MAGIC LASTEDITDATEINDIVIDUALCUSTOMER	STRING,
# MAGIC HOMEPHONE_CORENONPOSTALADDRESSSYSID	STRING,
# MAGIC HOMEPHONE_PHONENUMBER	STRING,
# MAGIC HOMEPHONE_LASTEDITDATEHOME	STRING,
# MAGIC HOMEPHONE_PHONETYPE	STRING,
# MAGIC WORKPHONE_CORENONPOSTALADDRESSSYSID	STRING,
# MAGIC WORKPHONE_LASTEDITDATEWORK	STRING,
# MAGIC WORKPHONE_PHONENUMBER	STRING,
# MAGIC WORKPHONE_PHONETYPE	STRING,
# MAGIC MOBILEPHONE_CORENONPOSTALADDRESSSYSID	STRING,
# MAGIC MOBILEPHONE_LASTEDITDATEMOBILE	STRING,
# MAGIC MOBILEPHONE_PHONENUMBER	STRING,
# MAGIC MOBILEPHONE_PHONETYPE	STRING,
# MAGIC CORRESPONDENCEADDRESS_COREADDRESSSYSID	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE1	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE2	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE3	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE4	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE5	STRING,
# MAGIC CORRESPONDENCEADDRESS_POSTCODE	STRING,
# MAGIC CORRESPONDENCEADDRESS_COUNTRYCODE	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSTYPECODE	STRING,
# MAGIC CORRESPONDENCEADDRESS_PAFSTATUS	STRING,
# MAGIC CORRESPONDENCEADDRESS_LASTEDITDATECORRESPONDENCEADDRESS	STRING,
# MAGIC EMAIL_CORENONPOSTALADDRESSSYSID	STRING,
# MAGIC EMAIL_EMAIL	STRING,
# MAGIC EMAIL_LASTEMAILENDDATE	STRING,
# MAGIC EMAIL_LASTEDITDATEEMAIL	STRING,
# MAGIC AGMEMAILOPTIN_OPTINVALUE	STRING,
# MAGIC AGMEMAILOPTIN_LASTEDITDATEAGMEMAILOPT	STRING,
# MAGIC EMAILOPTIN_OPTINVALUE	STRING,
# MAGIC EMAILOPTIN_LASTEDITDATEEMAILOPT	STRING,
# MAGIC MAILOPTIN_OPTINVALUE	STRING,
# MAGIC MAILOPTIN_LASTEDITDATEMAILOPT	STRING,
# MAGIC TELOPTIN_OPTINVALUE	STRING,
# MAGIC TELOPTIN_LASTEDITDATETELOPT	STRING,
# MAGIC BATCH_ID	STRING,
# MAGIC FILE_NAME	STRING,
# MAGIC LOAD_DATE TIMESTAMP,
# MAGIC SOURCE_SYSTEM STRING,
# MAGIC CASTING_VALIDATION_RESULT STRING,
# MAGIC RULE_VALIDATION_RESULT STRING);

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVBRONZE.bronze_staging.CUSTOMER_BRONZE_HISTORY
# MAGIC (
# MAGIC HISTORY_ID 	STRING,
# MAGIC ID	STRING,
# MAGIC EVENTTYPE STRING,
# MAGIC SOURCERECORDID	STRING,
# MAGIC SOURCESYSTEMID	STRING,
# MAGIC TITLE	STRING,
# MAGIC FORENAMES	STRING,
# MAGIC LASTNAME	STRING,
# MAGIC PERSONALNAMESUFFIX	STRING,
# MAGIC BIRTHDATE	STRING,
# MAGIC GENDER	STRING,
# MAGIC NATIONALINSURANCENUMBER	STRING,
# MAGIC NATIONALITY	STRING,
# MAGIC MARITALSTATUS	STRING,
# MAGIC EXCLUDEFROMDEDUPE	STRING,
# MAGIC TAXIDNUMBER	STRING,
# MAGIC TAXDOMICILE	STRING,
# MAGIC DEATHEVIDENCESEENDATE	STRING,
# MAGIC DECEASEDDATE	STRING,
# MAGIC DECEASEDNOTIFICATIONDATE	STRING,
# MAGIC DEACTIVATEDRECORD	STRING,
# MAGIC RELATIONSHIPENDDATE	STRING,
# MAGIC RELATIONSHIPSTARTDATE	STRING,
# MAGIC SENTFORDELETIONDATE	STRING,
# MAGIC SENTFORDELETIONUSER	STRING,
# MAGIC DELETEDINCORE	STRING,
# MAGIC DELETEDINMDM	STRING,
# MAGIC DELETIONDEDUPEEXCLUSION	STRING,
# MAGIC DORMANTACCOUNTFLAG	STRING,
# MAGIC MANUALEXCEPTIONFLAG	STRING,
# MAGIC MANUALEXCEPTIONREASON	STRING,
# MAGIC MANUALEXCEPTIONUSER	STRING,
# MAGIC MCNRFLAG	STRING,
# MAGIC OPENCOMPLAINTFLAG	STRING,
# MAGIC OPENLITIGATIONFLAG	STRING,
# MAGIC LASTEDITDATEINDIVIDUALCUSTOMER	STRING,
# MAGIC HOMEPHONE_CORENONPOSTALADDRESSSYSID	STRING,
# MAGIC HOMEPHONE_PHONENUMBER	STRING,
# MAGIC HOMEPHONE_LASTEDITDATEHOME	STRING,
# MAGIC HOMEPHONE_PHONETYPE	STRING,
# MAGIC WORKPHONE_CORENONPOSTALADDRESSSYSID	STRING,
# MAGIC WORKPHONE_LASTEDITDATEWORK	STRING,
# MAGIC WORKPHONE_PHONENUMBER	STRING,
# MAGIC WORKPHONE_PHONETYPE	STRING,
# MAGIC MOBILEPHONE_CORENONPOSTALADDRESSSYSID	STRING,
# MAGIC MOBILEPHONE_LASTEDITDATEMOBILE	STRING,
# MAGIC MOBILEPHONE_PHONENUMBER	STRING,
# MAGIC MOBILEPHONE_PHONETYPE	STRING,
# MAGIC CORRESPONDENCEADDRESS_COREADDRESSSYSID	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE1	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE2	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE3	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE4	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSLINE5	STRING,
# MAGIC CORRESPONDENCEADDRESS_POSTCODE	STRING,
# MAGIC CORRESPONDENCEADDRESS_COUNTRYCODE	STRING,
# MAGIC CORRESPONDENCEADDRESS_ADDRESSTYPECODE	STRING,
# MAGIC CORRESPONDENCEADDRESS_PAFSTATUS	STRING,
# MAGIC CORRESPONDENCEADDRESS_LASTEDITDATECORRESPONDENCEADDRESS	STRING,
# MAGIC EMAIL_CORENONPOSTALADDRESSSYSID	STRING,
# MAGIC EMAIL_EMAIL	STRING,
# MAGIC EMAIL_LASTEMAILENDDATE	STRING,
# MAGIC EMAIL_LASTEDITDATEEMAIL	STRING,
# MAGIC AGMEMAILOPTIN_OPTINVALUE	STRING,
# MAGIC AGMEMAILOPTIN_LASTEDITDATEAGMEMAILOPT	STRING,
# MAGIC EMAILOPTIN_OPTINVALUE	STRING,
# MAGIC EMAILOPTIN_LASTEDITDATEEMAILOPT	STRING,
# MAGIC MAILOPTIN_OPTINVALUE	STRING,
# MAGIC MAILOPTIN_LASTEDITDATEMAILOPT	STRING,
# MAGIC TELOPTIN_OPTINVALUE	STRING,
# MAGIC TELOPTIN_LASTEDITDATETELOPT	STRING,
# MAGIC BATCH_ID	STRING,
# MAGIC FILE_NAME	STRING,
# MAGIC LOAD_DATE TIMESTAMP,
# MAGIC SOURCE_SYSTEM STRING,
# MAGIC CASTING_VALIDATION_RESULT STRING,
# MAGIC RULE_VALIDATION_RESULT STRING);

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVSILVER.silver.POSTAL_ADDRESSES
# MAGIC (
# MAGIC 	SYSID BIGINT NOT NULL ,
# MAGIC 	PARTY_MDM_ID VARCHAR(40) NOT NULL ,
# MAGIC 	ADDRESS_TYPE_CODE VARCHAR(6) NOT NULL ,
# MAGIC 	LINE_1 VARCHAR(35) NOT NULL ,
# MAGIC 	LINE_2 VARCHAR(35)  ,
# MAGIC 	LINE_3 VARCHAR(35)  ,
# MAGIC 	LINE_4 VARCHAR(35)  ,
# MAGIC 	LINE_5 VARCHAR(35)  ,
# MAGIC 	COUNTRY_CODE VARCHAR(6)  ,
# MAGIC 	POSTCODE VARCHAR(7)  ,
# MAGIC 	PAF_STATUS VARCHAR(6)  ,
# MAGIC 	VALID_FROM TIMESTAMP NOT NULL ,
# MAGIC 	VALID_TO TIMESTAMP  ,
# MAGIC 	HASH_VALUE VARCHAR(256)  ,
# MAGIC 	DELETED_FLAG VARCHAR(1)  ,
# MAGIC 	BATCH_ID VARCHAR(256) NOT NULL 
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVSILVER.silver.PHONE_NUMBERS
# MAGIC (
# MAGIC 	SYSID BIGINT NOT NULL ,
# MAGIC 	PARTY_MDM_ID VARCHAR(40) NOT NULL ,
# MAGIC 	PHONE_TYPE_CODE VARCHAR(10) NOT NULL ,
# MAGIC 	PHONE_NUMBER VARCHAR(50) NOT NULL ,
# MAGIC 	COUNTRY_CODE VARCHAR(6)  ,
# MAGIC 	VALID_FROM TIMESTAMP NOT NULL ,
# MAGIC 	VALID_TO TIMESTAMP  ,
# MAGIC 	HASH_VALUE VARCHAR(256)  ,
# MAGIC 	DELETED_FLAG VARCHAR(1)  ,
# MAGIC 	BATCH_ID VARCHAR(256) NOT NULL 
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVSILVER.silver.EMAIL_ADDRESSES
# MAGIC (
# MAGIC 	SYSID BIGINT NOT NULL ,
# MAGIC 	PARTY_MDM_ID VARCHAR(40) NOT NULL ,
# MAGIC 	EMAIL VARCHAR(70) NOT NULL ,
# MAGIC 	VALID_FROM TIMESTAMP NOT NULL ,
# MAGIC 	VALID_TO TIMESTAMP,
# MAGIC 	HASH_VALUE VARCHAR(256) ,
# MAGIC 	DELETED_FLAG VARCHAR(1) ,
# MAGIC 	BATCH_ID VARCHAR(256) NOT NULL 
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVSILVER.silver.COMMUNICATION_PREFERENCES
# MAGIC (
# MAGIC 	SYSID BIGINT NOT NULL,
# MAGIC 	PARTY_MDM_ID VARCHAR(40) NOT NULL ,
# MAGIC 	COMM_CHANNEL_CODE VARCHAR(10) NOT NULL ,
# MAGIC 	OPT_IN_FLAG VARCHAR(1),
# MAGIC 	PREFERRED_COMM_METHOD_FLAG VARCHAR(6) ,
# MAGIC 	VALID_FROM TIMESTAMP NOT NULL ,
# MAGIC 	VALID_TO TIMESTAMP ,
# MAGIC 	HASH_VALUE VARCHAR(256),
# MAGIC 	DELETED_FLAG VARCHAR(1),
# MAGIC 	BATCH_ID VARCHAR(256) NOT NULL 
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVSILVER.silver.PARTIES
# MAGIC (
# MAGIC 	PARTY_MDM_ID VARCHAR(40) NOT NULL ,
# MAGIC 	STATUS VARCHAR(20)  ,
# MAGIC 	HASH_VALUE VARCHAR(256)  ,
# MAGIC 	DELETED_FLAG VARCHAR(1)  ,
# MAGIC 	INSERTED_DATE TIMESTAMP NOT NULL ,
# MAGIC 	UPDATED_DATE TIMESTAMP  ,
# MAGIC 	BATCH_ID VARCHAR(256) NOT NULL 
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVSILVER.silver.PARTY_NATIONALITIES
# MAGIC (
# MAGIC 	SYSID BIGINT NOT NULL ,
# MAGIC 	PARTY_MDM_ID VARCHAR(40) NOT NULL ,
# MAGIC 	NATIONALITY_CODE VARCHAR(6) NOT NULL ,
# MAGIC 	FIRST_DECLARED_NTNLTY_FLAG VARCHAR(1) NOT NULL ,
# MAGIC 	VALID_FROM TIMESTAMP NOT NULL ,
# MAGIC 	VALID_TO TIMESTAMP  ,
# MAGIC 	HASH_VALUE VARCHAR(256)  ,
# MAGIC 	DELETED_FLAG VARCHAR(1)  ,
# MAGIC 	BATCH_ID VARCHAR(256) NOT NULL 
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVSILVER.silver.PARTY_REFERENCES
# MAGIC (
# MAGIC 	SYSID BIGINT NOT NULL ,
# MAGIC 	PARTY_MDM_ID VARCHAR(40) NOT NULL ,
# MAGIC 	SOURCE_PARTY_ID VARCHAR(4000) NOT NULL ,
# MAGIC 	SOURCE VARCHAR(100) NOT NULL ,
# MAGIC 	HASH_VALUE VARCHAR(256)  ,
# MAGIC 	DELETED_FLAG VARCHAR(1)  ,
# MAGIC 	INSERTED_DATE TIMESTAMP NOT NULL ,
# MAGIC 	UPDATED_DATE TIMESTAMP  ,
# MAGIC 	BATCH_ID VARCHAR(256) NOT NULL 
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE TABLE IF NOT EXISTS LHDEVSILVER.silver.PEOPLE
# MAGIC (
# MAGIC 	SYSID BIGINT NOT NULL ,
# MAGIC 	PARTY_MDM_ID VARCHAR(40) NOT NULL ,
# MAGIC 	FIRST_NAMES VARCHAR(70)  ,
# MAGIC 	LAST_NAME VARCHAR(70)  ,
# MAGIC 	TITLE_CODE VARCHAR(7)  ,
# MAGIC 	SUFFIX VARCHAR(30)  ,
# MAGIC 	GENDER_CODE VARCHAR(1)  ,
# MAGIC 	DATE_OF_BIRTH DATE  ,
# MAGIC 	MARITAL_STATUS_CODE VARCHAR(6)  ,
# MAGIC 	NATIONAL_INSURANCE_NUMBER VARCHAR(9)  ,
# MAGIC 	TAX_DOMICILE_CODE VARCHAR(6)  ,
# MAGIC 	TAX_ID_NUMBER VARCHAR(30)  ,
# MAGIC 	FATCA_ELIGIBLE VARCHAR(1) ,
# MAGIC 	RELATIONSHIP_START_DATE TIMESTAMP  ,
# MAGIC 	RELATIONSHIP_END_DATE TIMESTAMP  ,
# MAGIC 	ASSUMED_VC VARCHAR(20)  ,
# MAGIC 	DORMANT_FLAG VARCHAR(1)  ,
# MAGIC 	DECEASED_DATE DATE  ,
# MAGIC 	DECEASED_NOTIFICATION_DATE DATE  ,
# MAGIC 	DECEASED_EVIDENCE_DATE DATE  ,
# MAGIC 	MCNR_DEBT_FLAG VARCHAR(1)  ,
# MAGIC 	OPEN_COMPLAINT_FLAG VARCHAR(1)  ,
# MAGIC 	OPEN_LITIGATION_FLAG VARCHAR(1)  ,
# MAGIC 	VALID_FROM TIMESTAMP NOT NULL ,
# MAGIC 	VALID_TO TIMESTAMP  ,
# MAGIC 	HASH_VALUE VARCHAR(256)  ,
# MAGIC 	DELETED_FLAG VARCHAR(1)  ,
# MAGIC 	BATCH_ID VARCHAR(256) NOT NULL 
# MAGIC );

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }
